version: "3"

services:   
  mongo:
    container_name: mongo_sw 
    image: mongo
    ports:
      - "27017:${MONGO_PORT}"
  api:
    container_name: swapi
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ${PWD}:/app
    environment:
      - "DATABASE=${DATABASE}"
      - "JWTPRIVATEKEY=${JWTPRIVATEKEY}"      
    depends_on:
      - mongo