version: "3"

services:   
  mongo:
    container_name: mongo_sw 
    image: mongo
    ports:
      - 27017:27017
  api:
    container_name: swapi
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ${PWD}:/app
    environment:
      - "SWAPI_DATABASE=${SWAPI_DATABASE}"
      - "SWAPI_PRIVATE_KEY=${SWAPI_PRIVATE_KEY}" 
      - "NODE_ENV=${NODE_ENV}"     
    depends_on:
      - mongo