version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINT
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST \<<'ENDSSH'
            cd /swapi
            git pull origin master
            rm package-lock.json
            docker build  -t swapi .
            docker rm -f swapi
            docker run --rm --network web --name swapi -e DATABASE=mongodb://mongo/star_wars_planets_db -e PORT=3001 -e JWTPRIVATEKEY=$JWTPRIVATEKEY -d swapi                              
            ENDSSH

  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mongo:latest
        environment: 
          DATABASE: mongodb://localhost/star_wars_planets_db

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: run test
          command: npm run test
          environment: 
            DATABASE: mongodb://localhost/star_wars_planets_db
      - run:
          name: Generate code coverage
          command: npm run coverage
      - store_artifacts:
          path: coverage
          prefix: coverage    
      - codecov/upload:
          file: coverage/lcov.info
workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test
      - deploy